name: digital_clock
description: Digital pixel clock.
version: 1.0.0+1
author: MSVCode (msvcode@gmail.com)

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  community_material_icon: 3.5.95

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
